# Generated by Django 4.2.11 on 2025-07-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('ALL', 'All Groups'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('area', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
