# Generated by Django 4.2.11 on 2025-07-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Patient Name')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Blood Group')),
                ('hospital_name', models.CharField(max_length=150, verbose_name='Hospital Name')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('required_date', models.DateField(verbose_name='Required Date')),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='Fulfilled')),
            ],
        ),
    ]
