# Generated by Django 4.2.11 on 2025-07-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=3, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hospital_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Hospital Name'),
        ),
    ]
